version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - nodeapp-data:/data/postgres
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisapp-data:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'

volumes:
  nodeapp-data:
  redisapp-data:
